django_rest_framework/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from auth import views as authviews
from rest_framework import routers

from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'users', authviews.UserViewSet)
router.register(r'groups', authviews.GroupViewSet)

urlpatterns = [
    # 'r' : regular expression
    # '^' : beginning
    # '$' : ending 
    # so r'^$' means when requested to individual app path, for example, 
    # http://127.0.0.1:8000/
	url(r'^', include(router.urls)),
    url(r'^admin/', admin.site.urls),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),    
    url(r'^example_api/', include('example_api.urls')),
    url(r'^samplepage/', include('samplepage.urls')),
    url(r'^music/', include('music.urls')),
]

# if debug mode(developer env)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'	# namespace of this urls.py


urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name="index"),	

	# 
	url(r'^register/$', views.UserFormView.as_view(), name="register"),	

	# /music/2/ 	album detail page id 2	
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'), 

	# /music/album/add/ 	to create album
	url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'), 

	# /music/album/2/ 		to update album id 2
	url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'), 

	# /music/album/2/delete/ to delete album id 2
	url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'), 		
]


# ###############################################################
# Deplicate code: Only for understand detail
# ###############################################################
# urlpatterns = [
# 	# /music/ :this is default homepage(index)
# 	url(r'^$', views.index, name="index"),		
#
# 	# /music/<album_id>/ :when <album_id> represent album_id that is a number ie: 1, 2, 500
# 	url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'), 
#
# 	# /music/<album_id>/favorite/ 
# 	url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'), 
# ]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse 

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.FileField(max_length=1000)		# FileField to keep files

	# method for CreateView
	def get_absolute_url(self):
		print(f"....CreateView at primary key: {self.pk}....")
		# pass primary key to detail page 
		return reverse('music:detail', kwargs={'pk': self.pk}) 

	# str dunder"(double underscore) methods: 
	# represent to string of this object
	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	# ForeignKey: link Song to Album database index
	# models.CASCADE: when delete Album then delete Song that linked to that Album 
	album = models.ForeignKey(Album, on_delete=models.CASCADE)	
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return f"{self.song_title}.{self.file_type} / {self.album.artist}"

music/forms.py
from django.contrib.auth.models import User 
from django import forms 

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User 
		fields = ['username', 'email', 'password']

music/views.py
###############################################################
# Using django generic views
###############################################################
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login
from django.views.generic import View 

from .models import Album 
from .forms import UserForm

# generic.ListView: to view the list of objects
class IndexView(generic.ListView):
	template_name = 'music/index.html' # plugin template
	context_object_name = 'all_albums' # overide default get_queryset return variable name: 
									   # 'object_list' to 'all_albums' that pass to template_name('music/index.html') 

	def get_queryset(self):
		return Album.objects.all()

# generic.DetialView: to view details of one object
class DetailView(generic.DetailView):
	template_name = 'music/detail.html' # plugin template
	model = Album 						# set object type for handler  
 	
# CreateView: class to create form for new object(ie: Album object)
class AlbumCreate(CreateView):
	model = Album 
	fields = ['artist', 'album_title', 'genre', 'album_logo']

# UpdateView: class to create form for update object(ie: Album object)
class AlbumUpdate(UpdateView):
	model = Album 
	fields = ['artist', 'album_title', 'genre', 'album_logo']

# DeleteView: class to Delete object handler
class AlbumDelete(DeleteView):
	model = Album 
	success_url = reverse_lazy('music:index')	# redirect to music/index page if success deleted

class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html' 

	# display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	# process form data: write data(from POST) to database
	def post(self, request):
		# get data that user input to form and POST
		form = self.form_class(request.POST)

		if form.is_valid():
			# storing to local object variable(user) but still NOT save to database yet
			user = form.save(commit=False)	

			# cleaned(normalized) data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)		# replace password have to call set_password()

			user.save()

			# return User objects if credentials are corrent
			user = authenticate(username=username, password=password)

			if user is not None:
				# check user is not in banned list
				if user.is_active:
					login(request, user)
					return redirect('music:index')

		# something is wrong! return blank form to user
		return render(request, self.template_name, {'form': form})

# ###############################################################
# Deplicate code: Only for understand detail
# ###############################################################
# #from django.http import Http404
# #from django.http import HttpResponse
# from django.shortcuts import render, get_object_or_404
# from .models import Album
#
# def index(request):
# 	all_albums = Album.objects.all()	# Use api to get all object in Album database 
# 	return render(request, 'music/index.html', {'all_albums': all_albums,})		
#
# 	#### same as
# 	# all_albums = Album.objects.all()	# Use api to get all object in Album database 
# 	# template = loader.get_template('music/index.html')
# 	# context = {
# 	# 	'all_albums': all_albums,
# 	# }
# 	# return HttpResponse(template.render(context, request))
#
# def detail(request, album_id):
# 	album = get_object_or_404(Album, pk=album_id)
# 	return render(request, 'music/detail.html', {'album': album})	
#
# 	#### same as
# 	# try:
# 	# 	album = Album.objects.get(pk=album_id)
# 	# except Album.DoesNotExist:
# 	# 	raise Http404("No Album matches the given query")
# 	# return render(request, 'music/detail.html', {'album': album})	
#
# def favorite(request, album_id):
# 	album = get_object_or_404(Album, pk=album_id)
# 	try:
# 		select_song = album.song_set.get(pk=request.POST['song'])
# 	except (KeyError, Song.DoesNotExist):
# 		return render(request, 'music/detail.html',
# 							{
# 								'album': album,
# 								'error_message': "You did not select a valid song",
# 							}
# 						)
# 	else:
# 		select_song.is_favorite = not select_song.is_favorite	# toggle
# 		select_song.save()
# 		return render(request, 'music/detail.html', {'album': album})
#

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new Album{% endblock title %}
{% block album_active %}active{% endblock album_active %}

{% block body %}
<div class="container-fluid">
	<div cass="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include "music/form-template.html" %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>

					</form>
				</div>
			</div>
		</div>
	<div>

{% endblock body %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
		OoRagNak Music		{# default value #}
		{% endblock title %}
	</title>
	{% load staticfiles %}	<!-- Loads the path to static files: music/static -->
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" >
	<link href="https://fonts.googleapis.com/css?family=Itim" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{%  static 'music/style.css' %}">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- Header -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>	
				<span class="icon-bar"></span>	
				<span class="icon-bar"></span>	
			</button>
			<a class="navbar-brand" href="{% url 'music:index' %}">OoRagNak</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
					</a>
				</li>
				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
					</a>
				</li>				
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">					
				</div>	
				<button type="submit" class="btn btn-default">Search</button>
			</form>

			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'music:album-add' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
					</a>
				</li>						
			</ul>

		</div>

	</dir>
</nav>
{% block body %}
{% endblock body %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock title %}
{% block albums_active %}active{% endblock albums_active %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock body %}








<!-- Backup UI version 0.1 -->
<!-- { % extends 'music/base.html' %}

{ % block title %}
	{{ album.album_title }} by {{ album.artist }}
{ % endblock title %}

{ % block body %}

	<img src="{{ album.album_logo }}" style="width: 250px;">
	
	<h1>{{ album.album_title }}</h1>
	<h3>{{ album.artist }}</h3>

	{% if error_message	%}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}

	{% for song in album.song_set.all %}
		{{ song.song_title }}.{{ song.file_type }}
		{% if song.is_favorite	%}
			<img src="http://i.imgur.com/b9b13Rd.png" />
		{% endif %}	
		<br>	
	{% endfor %}

{ % endblock body %} -->

	<!-- Backup -->
	<!-- Deplicate: only for example, not proper way to favorite songs  -->
	<!-- https://www.blognone.com/node/37959 -->
	<!-- <form action="{% url 'music:favorite' album.id %}" method="post">
		{% csrf_token %}	
		{% for song in album.song_set.all %}
			<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
			<label for="song{{ forloop.counter }}">
				{{ song.song_title }}
				{% if song.is_favorite	%}
					<img src="http://i.imgur.com/b9b13Rd.png" />
				{% endif %}
			</label><br>
		{% endfor %}
		<input type="submit" value="Favorite">
	</form> -->

music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offet-2 col-sm-10">
			<span class="col-sm-10 text-danger small">{{ field.errors }}</span>
		</div>
		<br>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>	
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock albums_active %}

{% block body %}
<div class="albums-container container-fluid">
    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s albums</h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive" style="width: 250px; height: 250px">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>

{% endblock body %}




<!-- Backup UI version 0.1 -->
<!-- 
{ % extends 'music/base.html' %}

{ % block body %}
	{% if all_albums %}
		<h3>Albums list</h3>
		<ul>
			{% for album in all_albums %}
				<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<h3>You don't have any albums</h3>
	{% endif %}
{ % endblock body %} -->

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock title %}
{% block album_active %}active{% endblock album_active %}

{% block body %}
<div class="container-fluid">
	<div cass="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Create a New Account</h3>
					{% if error_message %}
						<p><strong>{{ error_message }}</strong></p>
					{% endif %}
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include "music/form-template.html" %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>

					</form>
				</div>
			</div>
		</div>
	<div>

{% endblock body %}